#!/bin/bash

# Create symlinks from the home directory to any dotfiles in ~/dotfiles
regex="[^/]*$"
for file in ~/dotfiles/.* # Only match hidden files
do
  if [[ -f $file ]]
  then
    if [[ $file =~ $regex ]]
    then
      filename="${BASH_REMATCH[0]}"
      rm ~/$filename
      ln -s $file ~/$filename
    fi
  fi
done

# Symlink VS Code config files
rm ~/Library/'Application Support'/Code/User/keybindings.json
rm ~/Library/'Application Support'/Code/User/settings.json
ln -s ~/dotfiles/vs_code/keybindings.json ~/Library/'Application Support'/Code/User/keybindings.json
ln -s ~/dotfiles/vs_code/settings.json ~/Library/'Application Support'/Code/User/settings.json

chsh -s /bin/zsh
echo "Done"
